name: exploration
channels:
  - pytorch3d
  - iopath
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.5.0=py39h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py39h06a4308_0
  - babel=2.11.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2023.5.7=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py39h06a4308_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.1.105=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.1.105=0
  - cuda-nsight-compute=12.1.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.1.105=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.1.105=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.1.105=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.1.105=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gds-tools=1.6.1.9=0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.0.0=py39h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - iopath=0.1.9=py39
  - ipykernel=6.19.2=py39hb070fc8_0
  - ipython=8.12.0=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py39h06a4308_0
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.1.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py39h06a4308_0
  - jupyter=1.0.0=py39h06a4308_8
  - jupyter_client=8.1.0=py39h06a4308_0
  - jupyter_console=6.6.3=py39h06a4308_0
  - jupyter_core=5.3.0=py39h06a4308_0
  - jupyter_server=1.23.4=py39h06a4308_0
  - jupyterlab=3.5.3=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py39h06a4308_0
  - jupyterlab_widgets=3.0.5=py39h06a4308_0
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.6.1.9=0
  - libcufile-dev=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcurand-dev=10.3.2.106=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.3=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - lxml=4.9.2=py39h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - nbclassic=0.5.5=py39h06a4308_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.5.4=py39h06a4308_0
  - nbformat=5.7.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py39h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.5.4=py39h06a4308_0
  - notebook-shim=0.2.2=py39h06a4308_0
  - nsight-compute=2023.1.1.4=0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numpy=1.24.3=py39hf6e8229_1
  - numpy-base=1.24.3=py39h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=py39h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.0.1=py39h06a4308_0
  - platformdirs=2.5.2=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - portalocker=2.7.0=py39hf3d152e_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39h06a4308_1
  - pyopenssl=23.0.0=py39h06a4308_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python_abi=3.9=2_cp39
  - pytorch=1.13.0=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.4=py39_cu116_pyt1130
  - pytz=2022.7=py39h06a4308_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=25.0.2=py39h6a678d5_0
  - qt-main=5.15.2=h8373d8f_8
  - qt-webengine=5.15.9=hbbf29b9_6
  - qtconsole=5.4.2=py39h06a4308_0
  - qtpy=2.2.0=py39h06a4308_0
  - qtwebkit=5.212=h3fafdc1_5
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py39h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=66.0.0=py39h06a4308_0
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py39h06a4308_1
  - soupsieve=2.4=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - terminado=0.17.1=py39h06a4308_0
  - tinycss2=1.2.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - torchvision=0.14.0=py39_cu116
  - tornado=6.2=py39h5eee18b_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.7.1=py39h06a4308_0
  - typing-extensions=4.5.0=py39h06a4308_0
  - typing_extensions=4.5.0=py39h06a4308_0
  - urllib3=1.26.15=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=0.58.0=py39h06a4308_4
  - wheel=0.38.4=py39h06a4308_0
  - widgetsnbextension=4.0.5=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==2.0.0
    - accelerate==0.30.1
    - aiofiles==23.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - altair==5.0.0
    - async-timeout==4.0.2
    - black==23.3.0
    - cachetools==5.3.2
    - click==8.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - decorator==4.4.2
    - fastapi==0.95.2
    - ffmpy==0.3.0
    - filelock==3.12.0
    - flake8==6.0.0
    - flake8-bugbear==23.5.9
    - flake8-comprehensions==3.12.0
    - fonttools==4.39.4
    - frozenlist==1.3.3
    - fsspec==2023.5.0
    - gdown==5.2.0
    - google-auth==2.25.2
    - google-auth-oauthlib==1.2.0
    - gradio==3.32.0
    - gradio-client==0.2.5
    - grpcio==1.60.0
    - h11==0.14.0
    - httpcore==0.17.2
    - httpx==0.24.1
    - huggingface-hub==0.14.1
    - imageio==2.29.0
    - imageio-ffmpeg==0.4.9
    - importlib-resources==5.12.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - libcst==1.0.0
    - linkify-it-py==2.0.2
    - lion-pytorch==0.1.2
    - lmdb==1.5.1
    - markdown==3.5.1
    - markdown-it-py==2.2.0
    - matplotlib==3.7.1
    - mccabe==0.7.0
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - moreorless==0.4.0
    - moviepy==1.0.3
    - msgpack==1.0.8
    - msgpack-numpy==0.4.8
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - networkx==3.1
    - oauthlib==3.2.2
    - opencv-python==4.7.0.72
    - orjson==3.8.14
    - pandas==2.0.1
    - pathspec==0.11.1
    - plotly==5.14.1
    - proglog==0.1.10
    - protobuf==4.23.4
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycodestyle==2.10.0
    - pydantic==1.10.8
    - pydub==0.25.1
    - pyflakes==3.0.1
    - pyglet==1.5.28
    - pyparsing==3.0.9
    - python-hostlist==1.23.0
    - python-multipart==0.0.6
    - pywavelets==1.4.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - rtree==1.3.0
    - safetensors==0.4.3
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - semantic-version==2.10.0
    - starlette==0.27.0
    - stdlibs==2022.10.9
    - tenacity==8.2.2
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - toolz==0.12.0
    - torch-geometric==2.5.3
    - torchsummary==1.5.1
    - trailrunner==1.4.0
    - trimesh==4.1.2
    - typing-inspect==0.9.0
    - tzdata==2023.3
    - uc-micro-py==1.0.2
    - usort==1.0.6
    - uvicorn==0.22.0
    - websockets==11.0.3
    - werkzeug==3.0.1
    - yarl==1.9.2